/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.OneLayerAtm;

import java.awt.*;
import java.awt.geom.*;
//import java.util.*;

/**
 *
 * @author Joel
 */
public class OneLayerAtmUI extends javax.swing.JFrame {

    /**
     * Creates new form TemperatureTrialsUI
     */
    public OneLayerAtmUI() {
        initComponents();
    }

    private int trigger = 0;
    private double copyfahsur = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        ModuleBase = new javax.swing.JPanel();
        ResButton = new javax.swing.JButton();
        RanButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        AtmLabel = new javax.swing.JLabel();
        SurLabel = new javax.swing.JLabel();
        AtmFrameK = new javax.swing.JPanel();
        AtmNumK = new javax.swing.JLabel();
        AtmFrame = new javax.swing.JPanel();
        AtmNum = new javax.swing.JLabel();
        SurFrame = new javax.swing.JPanel();
        SurNum = new javax.swing.JLabel();
        SurFrameK = new javax.swing.JPanel();
        SurNumK = new javax.swing.JLabel();
        TempsColor = new javax.swing.JPanel();
        EnvFrame = new javax.swing.JPanel();
        EnvWords = new javax.swing.JLabel();
        ModuleFrame = new javax.swing.JPanel();
        ModuleTitle = new javax.swing.JLabel();
        ModuleSubT = new javax.swing.JLabel();
        RadSlider = new javax.swing.JSlider();
        RadLabel = new javax.swing.JLabel();
        RadColor = new javax.swing.JPanel();
        RadFrame = new javax.swing.JPanel();
        RadNum = new javax.swing.JLabel();
        AlbSlider = new javax.swing.JSlider();
        AlbLabel = new javax.swing.JLabel();
        AlbColor = new javax.swing.JPanel();
        AlbFrame = new javax.swing.JPanel();
        AlbNum = new javax.swing.JLabel();
        EmiSlider = new javax.swing.JSlider();
        EmiLabel = new javax.swing.JLabel();
        EmiColor = new javax.swing.JPanel();
        EmiFrame = new javax.swing.JPanel();
        EmiNum = new javax.swing.JLabel();
        CreditA = new javax.swing.JLabel();
        CreditB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModuleBase.setBackground(java.awt.Color.black);
        ModuleBase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.gray));

        ResButton.setBackground(java.awt.Color.black);
        ResButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ResButton.setForeground(java.awt.Color.white);
        ResButton.setText("Earth");
        ResButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ResButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResButtonActionPerformed(evt);
            }
        });

        RanButton.setBackground(java.awt.Color.black);
        RanButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RanButton.setForeground(java.awt.Color.white);
        RanButton.setText("Randomize");
        RanButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        RanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RanButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(java.awt.Color.black);
        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ExitButton.setForeground(java.awt.Color.white);
        ExitButton.setText("Exit");
        ExitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        AtmLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AtmLabel.setForeground(java.awt.Color.white);
        AtmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AtmLabel.setText("Atmos. Temperature");

        SurLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SurLabel.setForeground(java.awt.Color.white);
        SurLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SurLabel.setText("Surface Temperature");

        AtmFrameK.setBackground(java.awt.Color.black);
        AtmFrameK.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.blue, java.awt.Color.gray));

        AtmNumK.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        AtmNumK.setForeground(java.awt.Color.white);
        AtmNumK.setText("???");

        javax.swing.GroupLayout AtmFrameKLayout = new javax.swing.GroupLayout(AtmFrameK);
        AtmFrameK.setLayout(AtmFrameKLayout);
        AtmFrameKLayout.setHorizontalGroup(
            AtmFrameKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AtmFrameKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AtmNumK, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );
        AtmFrameKLayout.setVerticalGroup(
            AtmFrameKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AtmNumK, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        AtmFrame.setBackground(java.awt.Color.black);
        AtmFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.blue, java.awt.Color.gray));

        AtmNum.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        AtmNum.setForeground(java.awt.Color.white);
        AtmNum.setText("???");

        javax.swing.GroupLayout AtmFrameLayout = new javax.swing.GroupLayout(AtmFrame);
        AtmFrame.setLayout(AtmFrameLayout);
        AtmFrameLayout.setHorizontalGroup(
            AtmFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AtmFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AtmNum, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );
        AtmFrameLayout.setVerticalGroup(
            AtmFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AtmNum, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        SurFrame.setBackground(java.awt.Color.black);
        SurFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.red, java.awt.Color.gray));

        SurNum.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        SurNum.setForeground(java.awt.Color.white);
        SurNum.setText("???");

        javax.swing.GroupLayout SurFrameLayout = new javax.swing.GroupLayout(SurFrame);
        SurFrame.setLayout(SurFrameLayout);
        SurFrameLayout.setHorizontalGroup(
            SurFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SurFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SurNum, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );
        SurFrameLayout.setVerticalGroup(
            SurFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SurNum, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        SurFrameK.setBackground(java.awt.Color.black);
        SurFrameK.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.red, java.awt.Color.gray));

        SurNumK.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        SurNumK.setForeground(java.awt.Color.white);
        SurNumK.setText("???");

        javax.swing.GroupLayout SurFrameKLayout = new javax.swing.GroupLayout(SurFrameK);
        SurFrameK.setLayout(SurFrameKLayout);
        SurFrameKLayout.setHorizontalGroup(
            SurFrameKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SurFrameKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SurNumK, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );
        SurFrameKLayout.setVerticalGroup(
            SurFrameKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SurNumK, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        TempsColor.setBackground(java.awt.Color.black);
        TempsColor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.gray));
        TempsColor.setMaximumSize(new java.awt.Dimension(102, 102));
        TempsColor.setMinimumSize(new java.awt.Dimension(102, 102));

        javax.swing.GroupLayout TempsColorLayout = new javax.swing.GroupLayout(TempsColor);
        TempsColor.setLayout(TempsColorLayout);
        TempsColorLayout.setHorizontalGroup(
            TempsColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TempsColorLayout.setVerticalGroup(
            TempsColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        EnvFrame.setBackground(java.awt.Color.black);
        EnvFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.orange, java.awt.Color.gray));

        EnvWords.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        EnvWords.setForeground(new java.awt.Color(255, 0, 0));
        EnvWords.setText("Please Press \"Earth\" or \"Randomize\"");

        javax.swing.GroupLayout EnvFrameLayout = new javax.swing.GroupLayout(EnvFrame);
        EnvFrame.setLayout(EnvFrameLayout);
        EnvFrameLayout.setHorizontalGroup(
            EnvFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnvFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EnvWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EnvFrameLayout.setVerticalGroup(
            EnvFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EnvWords, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        ModuleFrame.setBackground(java.awt.Color.black);
        ModuleFrame.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, java.awt.Color.lightGray), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.gray)));

        ModuleTitle.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        ModuleTitle.setForeground(java.awt.Color.white);
        ModuleTitle.setText("Clime-App");

        ModuleSubT.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        ModuleSubT.setForeground(java.awt.Color.white);
        ModuleSubT.setText("The Climate Applet");

        javax.swing.GroupLayout ModuleFrameLayout = new javax.swing.GroupLayout(ModuleFrame);
        ModuleFrame.setLayout(ModuleFrameLayout);
        ModuleFrameLayout.setHorizontalGroup(
            ModuleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModuleFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModuleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ModuleSubT)
                    .addComponent(ModuleTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModuleFrameLayout.setVerticalGroup(
            ModuleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModuleFrameLayout.createSequentialGroup()
                .addComponent(ModuleTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ModuleSubT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        RadSlider.setMajorTickSpacing(1000);
        RadSlider.setMaximum(10000);
        RadSlider.setMinorTickSpacing(500);
        RadSlider.setPaintTicks(true);
        RadSlider.setValue(0);
        RadSlider.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(127, 127, 0)));
        RadSlider.setEnabled(false);
        RadSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadSliderStateChanged(evt);
            }
        });

        RadLabel.setBackground(new java.awt.Color(255, 255, 102));
        RadLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RadLabel.setForeground(java.awt.Color.white);
        RadLabel.setText("Incoming Stellar Radiation");

        RadColor.setBackground(new java.awt.Color(0, 0, 0));
        RadColor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));
        RadColor.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout RadColorLayout = new javax.swing.GroupLayout(RadColor);
        RadColor.setLayout(RadColorLayout);
        RadColorLayout.setHorizontalGroup(
            RadColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        RadColorLayout.setVerticalGroup(
            RadColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        RadFrame.setBackground(java.awt.Color.black);
        RadFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.yellow, java.awt.Color.gray));

        RadNum.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        RadNum.setForeground(java.awt.Color.white);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, RadSlider, org.jdesktop.beansbinding.ELProperty.create("${value/1000}"), RadNum, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout RadFrameLayout = new javax.swing.GroupLayout(RadFrame);
        RadFrame.setLayout(RadFrameLayout);
        RadFrameLayout.setHorizontalGroup(
            RadFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RadFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadNum, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );
        RadFrameLayout.setVerticalGroup(
            RadFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RadNum, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        AlbSlider.setMajorTickSpacing(100);
        AlbSlider.setMaximum(1000);
        AlbSlider.setMinorTickSpacing(50);
        AlbSlider.setPaintTicks(true);
        AlbSlider.setValue(0);
        AlbSlider.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 127, 0)));
        AlbSlider.setEnabled(false);
        AlbSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AlbSliderStateChanged(evt);
            }
        });

        AlbLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AlbLabel.setForeground(java.awt.Color.white);
        AlbLabel.setText("Planetary Albedo");

        AlbColor.setBackground(new java.awt.Color(0, 0, 0));
        AlbColor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout AlbColorLayout = new javax.swing.GroupLayout(AlbColor);
        AlbColor.setLayout(AlbColorLayout);
        AlbColorLayout.setHorizontalGroup(
            AlbColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        AlbColorLayout.setVerticalGroup(
            AlbColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        AlbFrame.setBackground(java.awt.Color.black);
        AlbFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.green, java.awt.Color.gray));

        AlbNum.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        AlbNum.setForeground(java.awt.Color.white);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, AlbSlider, org.jdesktop.beansbinding.ELProperty.create("${value/1000}"), AlbNum, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout AlbFrameLayout = new javax.swing.GroupLayout(AlbFrame);
        AlbFrame.setLayout(AlbFrameLayout);
        AlbFrameLayout.setHorizontalGroup(
            AlbFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlbFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AlbNum, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );
        AlbFrameLayout.setVerticalGroup(
            AlbFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AlbNum, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        EmiSlider.setMajorTickSpacing(100);
        EmiSlider.setMaximum(1000);
        EmiSlider.setMinorTickSpacing(50);
        EmiSlider.setPaintTicks(true);
        EmiSlider.setValue(0);
        EmiSlider.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 127, 127)));
        EmiSlider.setEnabled(false);
        EmiSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                EmiSliderStateChanged(evt);
            }
        });

        EmiLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmiLabel.setForeground(java.awt.Color.white);
        EmiLabel.setText("Atmosphere Emissivity");

        EmiColor.setBackground(new java.awt.Color(0, 0, 0));
        EmiColor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout EmiColorLayout = new javax.swing.GroupLayout(EmiColor);
        EmiColor.setLayout(EmiColorLayout);
        EmiColorLayout.setHorizontalGroup(
            EmiColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        EmiColorLayout.setVerticalGroup(
            EmiColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        EmiFrame.setBackground(java.awt.Color.black);
        EmiFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.cyan, java.awt.Color.gray));

        EmiNum.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        EmiNum.setForeground(java.awt.Color.white);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, EmiSlider, org.jdesktop.beansbinding.ELProperty.create("${value/1000}"), EmiNum, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout EmiFrameLayout = new javax.swing.GroupLayout(EmiFrame);
        EmiFrame.setLayout(EmiFrameLayout);
        EmiFrameLayout.setHorizontalGroup(
            EmiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmiFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmiNum, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );
        EmiFrameLayout.setVerticalGroup(
            EmiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmiNum, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        CreditA.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        CreditA.setForeground(java.awt.Color.lightGray);
        CreditA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CreditA.setText("J. C. Schwartz");

        CreditB.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        CreditB.setForeground(java.awt.Color.lightGray);
        CreditB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreditB.setText("2014,2017 ");

        javax.swing.GroupLayout ModuleBaseLayout = new javax.swing.GroupLayout(ModuleBase);
        ModuleBase.setLayout(ModuleBaseLayout);
        ModuleBaseLayout.setHorizontalGroup(
            ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModuleBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnvFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ModuleBaseLayout.createSequentialGroup()
                        .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModuleBaseLayout.createSequentialGroup()
                                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ModuleBaseLayout.createSequentialGroup()
                                        .addComponent(AlbLabel)
                                        .addGap(128, 128, 128)
                                        .addComponent(AlbFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(AlbSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(AlbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ModuleBaseLayout.createSequentialGroup()
                                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ModuleBaseLayout.createSequentialGroup()
                                        .addComponent(EmiLabel)
                                        .addGap(83, 83, 83)
                                        .addComponent(EmiFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EmiSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(EmiColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ModuleBaseLayout.createSequentialGroup()
                                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AtmFrameK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SurFrameK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AtmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AtmFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SurFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(TempsColor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ModuleBaseLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(ResButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ModuleBaseLayout.createSequentialGroup()
                                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(ModuleBaseLayout.createSequentialGroup()
                                        .addComponent(CreditA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ModuleFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ModuleBaseLayout.createSequentialGroup()
                                        .addComponent(RadLabel)
                                        .addGap(53, 53, 53)
                                        .addComponent(RadFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(RadSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RadColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CreditB))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModuleBaseLayout.setVerticalGroup(
            ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModuleBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModuleFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreditA)
                    .addComponent(CreditB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModuleBaseLayout.createSequentialGroup()
                        .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModuleBaseLayout.createSequentialGroup()
                                .addComponent(RadFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModuleBaseLayout.createSequentialGroup()
                                .addComponent(RadLabel)
                                .addGap(18, 18, 18)))
                        .addComponent(RadSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RadColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModuleBaseLayout.createSequentialGroup()
                        .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModuleBaseLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(AlbLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AlbFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(AlbSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AlbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModuleBaseLayout.createSequentialGroup()
                        .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModuleBaseLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(EmiLabel))
                            .addComponent(EmiFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(EmiSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EmiColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnvFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModuleBaseLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(AtmLabel)
                            .addComponent(AtmFrameK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AtmFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(SurLabel)
                            .addComponent(SurFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurFrameK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(TempsColor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModuleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ResButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(ModuleBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 700));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ResButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResButtonActionPerformed
        if (trigger == 0) {
            EnableParts();
            trigger = 1;
        }
        RadSlider.setValue(1000);
        AlbSlider.setValue(300);
        EmiSlider.setValue(750);
        BackCalcs();
    }//GEN-LAST:event_ResButtonActionPerformed

    private void RadSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadSliderStateChanged
        RadDraw();
        BackCalcs();
    }//GEN-LAST:event_RadSliderStateChanged

    private void AlbSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AlbSliderStateChanged
        AlbDraw();
        BackCalcs();
    }//GEN-LAST:event_AlbSliderStateChanged

    private void EmiSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_EmiSliderStateChanged
        EmiDraw();
        BackCalcs();
    }//GEN-LAST:event_EmiSliderStateChanged

    private void RanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RanButtonActionPerformed
        if (trigger == 0) {
            EnableParts();
            trigger = 1;
        }
        RadSlider.setValue(Math.round((float) Math.random() * 10000));
        AlbSlider.setValue(Math.round((float) Math.random() * 1000));
        EmiSlider.setValue(Math.round((float) Math.random() * 1000));
        BackCalcs();
    }//GEN-LAST:event_RanButtonActionPerformed
   
    public void EnableParts() {
        RadSlider.setEnabled(true);
        AlbSlider.setEnabled(true);
        EmiSlider.setEnabled(true);
        EnvWords.setForeground(Color.white);
    }
    
    public void RadDraw() {
        Graphics2D g2r = (Graphics2D)RadColor.getGraphics();
        int widthr = RadColor.getWidth();
        int heightr = RadColor.getHeight();
        g2r.setColor(Color.black);
        g2r.fillRect( 0, 0, widthr, heightr );
        double radlevel = Double.parseDouble(RadNum.getText()) / 10;
        for ( int i = 1; i <= 20; ++i ) {
            double radlowbound = ( 0.85 * (i - 1) / 19 );
            if (radlevel < radlowbound ) {
                g2r.setColor(Color.black);
            } else if (radlevel < (radlowbound + 0.15) ) {
                g2r.setColor(new Color( (float) 1, (float) 1, (float) 0, (float) (radlevel - radlowbound) * 100 / 15 ));
            } else {
                g2r.setColor(new Color( (float) 1, (float) 1, (float) 0, (float) 1 ));
            }
            g2r.drawLine( 4 * i - 4, 0, 4 * i + 12, 100 );
        }
        g2r.setColor(Color.lightGray);
        g2r.fillArc( -150, 75, 400, 400, 0, 180 );
    }
    
    public void AlbDraw() {
        Graphics2D g2a = (Graphics2D)AlbColor.getGraphics();
        int widtha = AlbColor.getWidth();
        int heighta = AlbColor.getHeight();
        g2a.setColor(Color.black);
        g2a.fillRect( 0, 0, widtha, heighta );
        double alblevel = Double.parseDouble(AlbNum.getText());
        g2a.setColor(new Color( (float) 1, (float) 1, (float) 0, (float) 1 ));
        g2a.fillOval( -widtha * 3/2, -heighta * 3/2, 2 * widtha, 2 * heighta );
        for ( int i = 1; i <= 3; ++i ) {
            g2a.drawLine( 5 * i - 10, 3, 5 * i + 40, 53 );
        }
        g2a.setColor(new Color( (float) 1, (float) 1, (float) 0, (float) alblevel ));
        for ( int i = 1; i <= 3; ++i ) {
            g2a.drawLine( 5 * i + 40, 53, 5 * i + 95, -2 );
        }
        g2a.setColor(new Color( (float) alblevel, (float) alblevel, (float) alblevel, (float) 1 ));
        g2a.fillOval( widtha/4, heighta/2, widtha/2, heighta/2 );
    }
    
    public void EmiDraw() {
        Graphics2D g2e = (Graphics2D)EmiColor.getGraphics();
        int widthe = EmiColor.getWidth();
        int heighte = EmiColor.getHeight();
        g2e.setColor(Color.black);
        g2e.fillRect( 0, 0, widthe, heighte );
        double emilevel = Double.parseDouble(EmiNum.getText());
        g2e.setColor(new Color( (float) 0, (float) 1, (float) 1, (float) emilevel ));
        g2e.fillArc( -175, 25, 450, 450, 0, 180 );
        g2e.setColor(Color.black);
        g2e.fillArc( -163, 50, 425, 425, 0, 180 );
        g2e.setColor(new Color( (float) 1, (float) 1, (float) 0, (float) 1 ));
        for ( int i = 1; i <= 3; ++i ) {
            g2e.drawLine( 5 * i - 5, 0, 5 * i + 15, 100 );
        }
        g2e.setColor(new Color( (float) 1, (float) 0, (float) 0, (float) 1 ));
        for ( int i = 1; i <= 3; ++i ) {
            g2e.drawLine( 5 * i + 10, 100, 5 * i + 25, 38 );
        }
        g2e.setColor(new Color( (float) 1, (float) 0, (float) 0, 1 - (float) emilevel ));
        for ( int i = 1; i <= 3; ++i ) {
            g2e.drawLine( 5 * i + 25, 39, 5 * i + 35, 0 );
        }
        g2e.setColor(new Color( (float) 1, (float) 0.4, (float) 0.4, (float) emilevel ));
        for ( int i = 1; i <= 3; ++i ) {
            g2e.drawLine( 5 * i + 50, 32, 5 * i + 70, 0 );
            g2e.drawLine( 5 * i + 50, 43, 5 * i + 80, 100 );
        }
        g2e.setColor(Color.lightGray);
        g2e.fillArc( -150, 75, 400, 400, 0, 180 );
    }
    
    public void BackCalcs() {
        double alb, emiss, sol;
        sol = Double.parseDouble(RadNum.getText()) * 1361/4;
        alb = Double.parseDouble(AlbNum.getText());
        emiss = Double.parseDouble(EmiNum.getText());
        double sur, atm, sigma;
        sigma = 5.67*Math.pow(10, -8);
        sur = Math.pow((2*sol*(1-alb))/(sigma*(2-emiss)), 0.25);
        double fahsur = (sur - 273.15) * 1.8 + 32;
        sur = Math.round(sur * 10);
        sur = sur / 10;
        fahsur = Math.round(fahsur * 10);
        fahsur = fahsur / 10;
        atm = Math.pow((sol*(1-alb))/(sigma*(2-emiss)), 0.25);
        double fahatm = (atm - 273.15) * 1.8 + 32;
        atm = Math.round(atm * 10);
        atm = atm / 10;
        fahatm = Math.round(fahatm * 10);
        fahatm = fahatm / 10;
        SurNumK.setText(String.valueOf(sur)+" K");
        SurNum.setText(String.valueOf(fahsur)+" F");
        if (emiss > 0) {
            AtmNumK.setText(String.valueOf(atm)+" K");
            AtmNum.setText(String.valueOf(fahatm)+" F");
        }
        else {
            AtmNumK.setText("NONE!!!");
            AtmNum.setText("NONE!!!");
        }
        copyfahsur = fahsur;
        double mysat;
        PlanetDraw();
        String env;
        if (sur >= 506) {
            EnvWords.setForeground(Color.red);
            env = "...And a book just burst into flames...";
        } else if (sur >= 423) {
            EnvWords.setForeground(Color.red);
            env = "Dead...but hey, we can bake cookies!";
        } else if (sur >= 373.15) {
            EnvWords.setForeground(Color.pink);
            env = "Parched? Have some boiling water!";
        } else if (sur >= 330) {
            EnvWords.setForeground(Color.pink);
            env = "It's hotter than any desert out there!";
        } else if (sur >= 300) {
            EnvWords.setForeground(Color.green);
            env = "OK, a hot summer day- not too bad...";
        } else if (sur >= 283) {
            EnvWords.setForeground(Color.green);
            env = "Ahhh- that's perfect Earth weather...";
        } else if (sur >= 273.15) {
            EnvWords.setForeground(Color.green);
            env = "It's getting a little bit chilly outside...";
        } else if (sur >= 250) {
            EnvWords.setForeground(Color.cyan);
            env = "...So now all the water froze. Hooray.";
        } else if (sur >= 185) {
            EnvWords.setForeground(Color.cyan);
            env = "Hey, everyone's a tasty popsicle now!";
        } else if (sur >= 100) {
            EnvWords.setForeground(Color.magenta);
            env = "Silly 'Antarctica' records...Avast Thou!";
        } else if (sur > 0) {
            EnvWords.setForeground(Color.magenta);
            env = "Cryo! Who likes heartbeats anyway?";
        } else {
            EnvWords.setForeground(Color.white);
            env = "Do thermometers even go this low?!";
        }
        EnvWords.setText(env);
    }
    
    public void PlanetDraw() {
        Graphics2D g2p = (Graphics2D)TempsColor.getGraphics();
        int widthp = TempsColor.getWidth();
        int heightp = TempsColor.getHeight();
        g2p.setColor(Color.black);
        g2p.fillRect( 0, 0, widthp, heightp );
        double pcolor;
        if (copyfahsur < 32) {
            pcolor = (32 - copyfahsur) / 492;
            g2p.setColor(Color.getHSBColor((float) (pcolor * 60 + 180)/360, (float) 0.9, (float) 0.9));
        }
        else if (copyfahsur < 68) {
            pcolor = (copyfahsur - 32) / 36;
            g2p.setColor(Color.getHSBColor((float) (180 - pcolor * 60)/360, (float) 0.9, (float) 0.9));
        }
        else if (copyfahsur < 212) {
            pcolor = (copyfahsur - 68) / 144;
            g2p.setColor(Color.getHSBColor((float) (120 - pcolor * 60)/360, (float) 0.9, (float) 0.9));
        }
        else {
            pcolor = (copyfahsur - 212) / 388;
            g2p.setColor(Color.getHSBColor((float) (60 - pcolor * 60)/360, (float) 0.9, (float) 0.9));
        }
        g2p.fillOval( widthp/4, heightp/4, widthp/2, heightp/2 );
        g2p.setColor(Color.black);
        double zeroang, angsp;
        if (copyfahsur < -125) {
            g2p.draw(new QuadCurve2D.Double( 35, 65, 50, 35, 65, 65 ));
            g2p.draw(new Line2D.Double( 40, 40, 45, 45 ));
            g2p.draw(new Line2D.Double( 40, 45, 45, 40 ));
            g2p.draw(new Line2D.Double( 55, 40, 60, 45 ));
            g2p.draw(new Line2D.Double( 55, 45, 60, 40 ));
        } else if (copyfahsur < -10) {
            zeroang = (12 * (125 + copyfahsur)) / 23;
            angsp = ((-24 * (125 + copyfahsur)) / 23) + 180;
            g2p.drawArc( 35, 55, 30, 20, (int) zeroang, (int) angsp );
            g2p.fill(new Ellipse2D.Double( 40, 40, 5, 5 ));
            g2p.fill(new Ellipse2D.Double( 55, 40, 5, 5 ));
        } else if (copyfahsur < 65) {
            zeroang = (12 * (copyfahsur - 65)) / 15;
            angsp = ((-8 * (copyfahsur - 65)) / 5) - 180;
            g2p.drawArc( 35, 45, 30, 20, (int) zeroang, (int) angsp );
            g2p.fill(new Ellipse2D.Double( 40, 40, 5, 5 ));
            g2p.fill(new Ellipse2D.Double( 55, 40, 5, 5 ));
        } else if (copyfahsur < 130) {
            zeroang = (-12 * (copyfahsur - 65)) / 13;
            angsp = ((24 * (copyfahsur - 65)) / 13) - 180;
            g2p.drawArc( 35, 45, 30, 20, (int) zeroang, (int) angsp );
            g2p.fill(new Ellipse2D.Double( 40, 40, 5, 5 ));
            g2p.fill(new Ellipse2D.Double( 55, 40, 5, 5 ));
        } else if (copyfahsur < 210) {
            zeroang = (-3 * (copyfahsur - 210)) / 4;
            angsp = ((3 * (copyfahsur - 210)) / 2) + 180;
            g2p.drawArc( 35, 55, 30, 20, (int) zeroang, (int) angsp );
            g2p.fill(new Ellipse2D.Double( 40, 40, 5, 5 ));
            g2p.fill(new Ellipse2D.Double( 55, 40, 5, 5 ));
        } else {
            g2p.draw(new QuadCurve2D.Double( 35, 65, 50, 35, 65, 65 ));
            g2p.draw(new Line2D.Double( 40, 40, 45, 45 ));
            g2p.draw(new Line2D.Double( 40, 45, 45, 40 ));
            g2p.draw(new Line2D.Double( 55, 40, 60, 45 ));
            g2p.draw(new Line2D.Double( 55, 45, 60, 40 ));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneLayerAtmUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OneLayerAtmUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlbColor;
    private javax.swing.JPanel AlbFrame;
    private javax.swing.JLabel AlbLabel;
    private javax.swing.JLabel AlbNum;
    private javax.swing.JSlider AlbSlider;
    private javax.swing.JPanel AtmFrame;
    private javax.swing.JPanel AtmFrameK;
    private javax.swing.JLabel AtmLabel;
    private javax.swing.JLabel AtmNum;
    private javax.swing.JLabel AtmNumK;
    private javax.swing.JLabel CreditA;
    private javax.swing.JLabel CreditB;
    private javax.swing.JPanel EmiColor;
    private javax.swing.JPanel EmiFrame;
    private javax.swing.JLabel EmiLabel;
    private javax.swing.JLabel EmiNum;
    private javax.swing.JSlider EmiSlider;
    private javax.swing.JPanel EnvFrame;
    private javax.swing.JLabel EnvWords;
    private javax.swing.JButton ExitButton;
    private javax.swing.JPanel ModuleBase;
    private javax.swing.JPanel ModuleFrame;
    private javax.swing.JLabel ModuleSubT;
    private javax.swing.JLabel ModuleTitle;
    private javax.swing.JPanel RadColor;
    private javax.swing.JPanel RadFrame;
    private javax.swing.JLabel RadLabel;
    private javax.swing.JLabel RadNum;
    private javax.swing.JSlider RadSlider;
    private javax.swing.JButton RanButton;
    private javax.swing.JButton ResButton;
    private javax.swing.JPanel SurFrame;
    private javax.swing.JPanel SurFrameK;
    private javax.swing.JLabel SurLabel;
    private javax.swing.JLabel SurNum;
    private javax.swing.JLabel SurNumK;
    private javax.swing.JPanel TempsColor;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
